language: cpp
compiler: g++

env:
- CFLAGS="-DNOGFX"

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots
- sudo apt-get update -qq

install:
- sudo apt-get install -qq libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev g++-4.8
- export CXX="g++-4.8"

script: make

notifications:
  email: false
